-- The schema as Hibernate's ddl-auto created it before Flyway took over.
-- Existing databases are baselined at this version and skip it; only a fresh
-- database runs it. Plain SQL so it runs on PostgreSQL and on the dev H2.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name  VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    full_name     VARCHAR(255) NOT NULL,
    joined_on     DATE         NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL CHECK (role IN ('ADMIN', 'USER')),
    status        VARCHAR(255) NOT NULL CHECK (status IN ('ACTIVE', 'LOCKED'))
);

CREATE TABLE account_request (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name  VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    full_name     VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    requested_on  DATE         NOT NULL
);

CREATE TABLE game (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_of_day INTEGER      NOT NULL,
    in_progress BOOLEAN      NOT NULL,
    majstorska  BOOLEAN      NOT NULL,
    note        VARCHAR(500),
    played_on   DATE         NOT NULL
);

CREATE TABLE game_player (
    game_id   BIGINT  NOT NULL REFERENCES game (id),
    player_id BIGINT  NOT NULL,
    seat      INTEGER NOT NULL CHECK (seat >= 0),
    PRIMARY KEY (game_id, seat)
);

CREATE TABLE game_money (
    game_id    BIGINT  NOT NULL REFERENCES game (id),
    amount_den INTEGER NOT NULL,
    player_id  BIGINT  NOT NULL
);

CREATE TABLE round (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment    VARCHAR(500),
    dealer_id  BIGINT  NOT NULL,
    hant       BOOLEAN NOT NULL,
    majstorska BOOLEAN NOT NULL,
    number     INTEGER NOT NULL,
    game_id    BIGINT  NOT NULL REFERENCES game (id)
);

CREATE TABLE round_entry (
    round_id   BIGINT       NOT NULL REFERENCES round (id),
    card_value INTEGER,
    outcome    VARCHAR(255) NOT NULL CHECK (outcome IN ('WINNER', 'OPENED', 'NOT_OPENED', 'QUIT')),
    player_id  BIGINT       NOT NULL,
    points     INTEGER      NOT NULL,
    seat       INTEGER      NOT NULL CHECK (seat >= 0),
    PRIMARY KEY (round_id, seat)
);
